# Generated by Django 4.2.26 on 2025-11-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Campaign name (e.g., 'New Product', 'Valentines Hampers')", max_length=100)),
                ('message', models.TextField(help_text='SMS message template. Use [Name] for personalization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Phone number of user who created this campaign', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this campaign template is active')),
            ],
            options={
                'verbose_name': 'Campaign Template',
                'verbose_name_plural': 'Campaign Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="List name (e.g., 'VIP Contacts', 'Test List')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this contact list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this list is active')),
                ('contacts', models.ManyToManyField(blank=True, help_text='Contacts in this list', related_name='contact_lists', to='app.contact')),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price (e.g., 99.99)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the product was added')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active and available')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The actual SMS message that was sent')),
                ('recipients_count', models.IntegerField(default=0, help_text='Number of recipients')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.CharField(blank=True, help_text='Phone number of user who sent this campaign', max_length=20)),
                ('api_response', models.TextField(blank=True, help_text="Response from Africa's Talking API", null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('campaign_template', models.ForeignKey(blank=True, help_text='The campaign template that was sent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.campaigntemplate')),
                ('contact_list', models.ForeignKey(blank=True, help_text='The contact list that received the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contactlist')),
            ],
            options={
                'verbose_name': 'Sent Campaign',
                'verbose_name_plural': 'Sent Campaigns',
                'ordering': ['-sent_at'],
            },
        ),
    ]
